PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS artist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  beginDate TEXT NOT NULL,
  endDate TEXT,
  location TEXT
);

CREATE TABLE IF NOT EXISTS genre (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "release" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  releaseDate TEXT NOT NULL,
  artistId INTEGER NOT NULL,
  genreId INTEGER,
  FOREIGN KEY (artistId) REFERENCES artist(id) ON DELETE CASCADE,
  FOREIGN KEY (genreId) REFERENCES genre(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS track (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  duration INTEGER NOT NULL,
  releaseId INTEGER NOT NULL,
  FOREIGN KEY (releaseId) REFERENCES "release"(id) ON DELETE CASCADE
);

COMMIT;
